apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/grounded-nebula-218907/github-niclan-kubernetes-intro:8edd8d0d7b4c515a4bb03e61c73cd3e02c2c0da2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
